//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suzy.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class avatar
    {
        public avatar()
        {
            this.accounts = new HashSet<account>();
            this.accounts1 = new HashSet<account>();
        }
    
        public int id { get; set; }
        public string avatar_src { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual ICollection<account> accounts1 { get; set; }
    }
}
