//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suzy.BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriber
    {
        public int id { get; set; }
        public int id_subscriber { get; set; }
        public int id_leader { get; set; }
    
        public virtual account account { get; set; }
        public virtual account account1 { get; set; }
    }
}
